---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: mavenhelloworld-deploy
spec:
    replicas: 1
    template:
      metadata:
       labels:
         app: mavenhelloworld-ctr
      spec:
         containers:
         - name: mavenhelloworld-pod
           image: docker.io/sumanthsainooka/mavenhelloworld-image:latest
           ports:
           - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata: 
  name: mavenhelloworld-svc
  labels:
    app: mavenhelloworld-ctr
spec:
  type: NodePort
  ports: 
  - port: 8080
    nodePort: 30006
    protocol: TCP
  selector:
    app: mavenhelloworld-ctr
---
