apiVersion: v1
kind: Service
metadata: 
  name: maven-helloworld-svc
  labels:
    app: maven-helloworld-ctr
spec:
  type: NodePort
  ports: 
  - port: 8080
    nodePort: 30006
    protocol: TCP
  selector:
    app: maven-helloworld-ctr
